# Generated by Django 2.0 on 2017-12-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'Mens'), ('W', 'Womens'), ('K', 'Kids'), ('U', 'Unisex')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
